spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diveintospringrest?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8080